services:
    backend:
        container_name: backend
        build:
            context: ./backend
        ports:
            - 5121:8080
        depends_on:
            - "database"
        networks:
            - network

    database:
        container_name: database
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: psexercise
        ports:
            - 5432:5432
        volumes:
            - ./database/data:/var/lib/postgresql/data
            - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - network

networks:
    network:
        driver: bridge
