services:
    aspnetapp:
        container_name: aspnetapp
        build:
            context: ./aspnetapp
        ports:
            - 5121:8080
        depends_on:
            - "postgresql"
        networks:
            - network

    postgresql:
        container_name: postgresql
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: psexercise
        ports:
            - 5432:5432
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
            - ./postgresql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - network

networks:
    network:
        driver: bridge
